name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://registry.npmjs.org'
    
    - name: Prepare
      run: |
        sudo apt-get install lsof
    # npm install codecov -g

    - name: Install
      run: |
        npm run clean:all
        npm run install:all

    # - name: Codecov
    #   run: codecov -t ${{ secrets.CODECOV_TOKEN }}

    - name: Build
      run: |
        npm run build:all

    - name: Test
      run: |
        npm run test

    - name: Integration Test
      run: |
        npm run cypress:test

    - name: Create version patch
      run: npm run update-version patch

    - name: Publish direflow-cli to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  
    - name: Publish direflow-component to NPM
      run: |
        cd packages/direflow-component
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  
    - name: Publish direflow-scripts to NPM
      run: |
        cd packages/direflow-scripts
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
